services:
  cointrack_backend:
    build:
      dockerfile: Dockerfile
    mem_limit: 4g
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash -c "python main.py"
    # command: tail -f /dev/null
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cointrack_network

  postgres:
    image: postgres:17-bullseye
    volumes:
      - postgres_cdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      retries: 5
    networks:
      - cointrack_network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - cointrack_network

networks:
  cointrack_network:
    driver: bridge

volumes:
  postgres_cdata:
